version: '3.3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/program
        links:
            - redis  
        depends_on:
            - redis
    redis:
        image: redis
