name: push-toaws.yml
on: [push]
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up --detach --build
      - name: Test with pytest
        run:  pytest