name: push-toaws.yml
on: [push]
jobs:
  pushDocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up --detach --build
      - name: Test with pytest
        run: |
          pip3 install pytest
          pip3 install requests
          pytest test_api.py
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chrispyoto/redisflaskapplication
          tag_with_ref: true


        
