name: push-toaws.yml
on: [push]
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up --detach --build
      - name: Test with pytest
        run: |
          pip3 install pytest
          pip3 install requests
          cd testing
          pytest test_api.py